"""Pure renderers that turn a :class:`~machina.introspect.core.Spine` into the
committed Form-A artifacts: a Markdown capability document and a
JSON-serializable dict.

Both functions are **pure**: they take a fully-built :class:`Spine` (and, for
Markdown, an opaque provenance string) and perform **no** git calls, no I/O,
and no unsorted iteration. Every collection on the :class:`Spine` already
arrives sorted from the core; the renderers preserve that order and never
re-sort into a different key, so two renders of the same :class:`Spine` are
byte-identical. The git SHA is obtained by the generator script
(:mod:`scripts.gen_spine`) and passed in, keeping determinism a property of the
renderer alone.

The seam free-text the renderers emit (Protocol/method docstrings) is already
path-scrubbed at the core (``machina.introspect.core._first_doc_line`` applies
``safe_text``), so the renderers add no further scrubbing.

Provenance header
-----------------
The Markdown carries a provenance block delimited by the HTML-comment markers
:data:`PROVENANCE_START` / :data:`PROVENANCE_END`. The drift gate strips
everything between (and including) those markers before comparing bodies, so a
changed git SHA never trips the gate. The markers are HTML comments, hence
invisible in rendered Markdown.
"""

from __future__ import annotations

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from machina.introspect.core import (
        CapabilityInfo,
        ConnectorInfo,
        Seams,
        Spine,
    )

# Provenance block delimiters. The drift gate (U3) strips the inclusive span
# between these markers before diffing, so the git SHA never causes a flap.
PROVENANCE_START = "<!-- PROVENANCE"
PROVENANCE_END = "PROVENANCE -->"

# Placeholder SHA used when git is unavailable (e.g. an sdist build outside a
# checkout). The generator passes the real ``git rev-parse HEAD`` when it can.
UNCOMMITTED_SHA = "uncommitted"


def render_provenance_header(git_sha: str) -> str:
    """Render the delimited provenance block (git SHA only, no timestamp).

    Args:
        git_sha: The commit SHA to stamp, or ``"uncommitted"`` when unknown.
            A wall-clock timestamp is deliberately **omitted** so the drift
            gate does not flap on every run.

    Returns:
        A single HTML-comment block delimited by :data:`PROVENANCE_START` /
        :data:`PROVENANCE_END`, safe to strip before a body diff.
    """
    sha = git_sha or UNCOMMITTED_SHA
    return (
        f"{PROVENANCE_START}\n"
        "Generated by scripts/gen_spine.py from machina.introspect.describe().\n"
        "Do not edit by hand — run `python scripts/gen_spine.py` to regenerate.\n"
        f"source_sha: {sha}\n"
        f"{PROVENANCE_END}"
    )


def strip_provenance(markdown: str) -> str:
    """Remove the provenance block from a rendered artifact for body diffing.

    Drops the inclusive span from :data:`PROVENANCE_START` to
    :data:`PROVENANCE_END` plus the single trailing newline, leaving the
    deterministic body the drift gate compares. Returns the input unchanged
    when no provenance block is present.

    Args:
        markdown: A rendered ``capabilities.md`` string.

    Returns:
        The artifact body with the provenance block removed.
    """
    start = markdown.find(PROVENANCE_START)
    if start == -1:
        return markdown
    end = markdown.find(PROVENANCE_END, start)
    if end == -1:
        return markdown
    end += len(PROVENANCE_END)
    # Swallow one trailing newline so the body starts cleanly.
    if end < len(markdown) and markdown[end] == "\n":
        end += 1
    return markdown[:start] + markdown[end:]


# ---------------------------------------------------------------------------
# JSON renderer
# ---------------------------------------------------------------------------


def render_json(spine: Spine) -> dict[str, Any]:
    """Render a :class:`Spine` to a JSON-serializable dict (provenance-free).

    The dict mirrors the spine structure 1:1 and preserves the core's sort
    order in every list. It carries no provenance (the generator attaches the
    SHA separately) so the body is stable across runs.

    Args:
        spine: The spine to serialize.

    Returns:
        A plain ``dict`` of built-in types, ready for ``json.dumps``.
    """
    return {
        # Schema discriminant: the MCP URI carries `v1`, but a cached payload
        # body must also self-identify so a consumer can tell v1 from a future
        # v2 without inspecting the transport. Additive; bump on breaking shape
        # changes only.
        "schema_version": "1",
        "connectors": [_connector_json(c) for c in spine.connectors],
        "capabilities": [_capability_json(c) for c in spine.capabilities],
        "seams": _seams_json(spine.seams),
        "config_schema": spine.config_schema,
        "gaps": {
            "orphaned_capabilities": list(spine.gaps.orphaned_capabilities),
            "unmapped_capabilities": list(spine.gaps.unmapped_capabilities),
            "settings_note": spine.gaps.settings_note,
        },
    }


def _connector_json(c: ConnectorInfo) -> dict[str, Any]:
    return {
        "type": c.type,
        "class_name": c.class_name,
        "dotted_path": c.dotted_path,
        "requires_extra": c.requires_extra,
        # NOTE: `extra_installed` is deliberately NOT serialized here. It is a
        # live environment fact (find_spec at call time), so baking it into the
        # committed, byte-compared artifact makes the drift gate flap across
        # environments (a full-extras dev box vs a bare CI job). `requires_extra`
        # (which extra is needed) is static and stays; whether it is installed
        # is answered live by `machina describe` (text view), not by the
        # portable JSON contract shared by the CLI, MCP resource, and artifact.
        "instance_computed": c.instance_computed,
        "degraded": c.degraded,
        "error": c.error,
        "capabilities": [
            {
                "capability": cc.capability,
                "method": cc.method,
                "configurable": cc.configurable,
            }
            for cc in c.capabilities
        ],
    }


def _capability_json(c: CapabilityInfo) -> dict[str, Any]:
    return {
        "value": c.value,
        "method": c.method,
        "provided_by": list(c.provided_by),
        "configurable_in": list(c.configurable_in),
        "orphaned": c.orphaned,
        "orphan_note": c.orphan_note,
    }


def _seams_json(seams: Seams) -> dict[str, Any]:
    return {
        "add_connector_template": seams.add_connector_template,
        "protocols": [
            {
                "name": p.name,
                "location": p.location,
                "doc": p.doc,
                "methods": [
                    {"name": m.name, "is_async": m.is_async, "doc": m.doc} for m in p.methods
                ],
            }
            for p in seams.protocols
        ],
        "conventions": [
            {
                "name": cv.name,
                "note": cv.note,
                "location_template": cv.location_template,
            }
            for cv in seams.conventions
        ],
    }


# ---------------------------------------------------------------------------
# Markdown renderer
# ---------------------------------------------------------------------------


def render_markdown(spine: Spine, git_sha: str = UNCOMMITTED_SHA) -> str:
    """Render a :class:`Spine` to the committed ``capabilities.md`` artifact.

    The document is, in order: the provenance header block, an intro, a
    capability x connector matrix, the seam manifest (protocols + conventions +
    add-connector template), and a config-schema summary. Every section
    iterates collections in the core's existing sort order — no new sorting is
    introduced — so the rendered body is deterministic for a given spine.

    Args:
        spine: The spine to render.
        git_sha: The commit SHA for the provenance header (default
            ``"uncommitted"``).

    Returns:
        The full Markdown artifact, provenance header included.
    """
    parts: list[str] = [
        render_provenance_header(git_sha),
        "",
        "# Machina capability matrix",
        "",
        (
            "Code-derived from `machina.introspect.describe()`. This file is "
            "**generated** — do not edit it by hand. Run `python "
            "scripts/gen_spine.py` to regenerate after changing connectors, "
            "capabilities, or seams."
        ),
        "",
        _render_matrix(spine.connectors, spine.capabilities),
        _render_capability_index(spine.capabilities),
        _render_seams(spine.seams),
        _render_config_summary(spine.config_schema),
        _render_gaps(spine),
    ]
    return "\n".join(parts).rstrip() + "\n"


def _render_matrix(
    connectors: tuple[ConnectorInfo, ...],
    capabilities: tuple[CapabilityInfo, ...],
) -> str:
    """Render the capability x connector matrix.

    A row per capability that at least one registered connector provides
    (live or configurable); a column per connector type. A cell is ``yes``
    (guaranteed live), ``cfg`` (configurable — needs the right config/backend),
    or empty. Capabilities with no registered provider are listed separately in
    the gaps section, never as an all-empty row.
    """
    conn_types = [c.type for c in connectors]
    # Map (capability_value, conn_type) -> "yes" | "cfg".
    cell: dict[tuple[str, str], str] = {}
    for conn in connectors:
        for cc in conn.capabilities:
            cell[(cc.capability, conn.type)] = "cfg" if cc.configurable else "yes"

    header = "| Capability | Method | " + " | ".join(conn_types) + " |"
    divider = "| --- | --- | " + " | ".join(["---"] * len(conn_types)) + " |"
    lines = ["## Capability x connector matrix", "", header, divider]
    for cap in capabilities:
        if cap.orphaned:
            continue
        row = [cap.value, f"`{cap.method}`" if cap.method else ""]
        for conn_type in conn_types:
            row.append(cell.get((cap.value, conn_type), ""))
        lines.append("| " + " | ".join(row) + " |")
    lines.append("")
    lines.append(
        "Legend: `yes` = declared and backed by a live method; `cfg` = available "
        "only under the right configuration/backend (annotated, not resolved — "
        "`describe()` runs without a config)."
    )
    lines.append("")
    return "\n".join(lines)


def _render_capability_index(capabilities: tuple[CapabilityInfo, ...]) -> str:
    """Render the per-capability provider index (which types serve each)."""
    lines = ["## Capabilities", ""]
    for cap in capabilities:
        if cap.orphaned:
            continue
        providers = ", ".join(cap.provided_by) if cap.provided_by else "—"
        configurable = ", ".join(cap.configurable_in) if cap.configurable_in else "—"
        method = f"`{cap.method}`" if cap.method else "—"
        lines.append(f"- **{cap.value}** (method {method})")
        lines.append(f"  - provided by: {providers}")
        if cap.configurable_in:
            lines.append(f"  - configurable in: {configurable}")
    lines.append("")
    return "\n".join(lines)


def _render_seams(seams: Seams) -> str:
    """Render the seam manifest: Protocol seams, conventions, and template."""
    lines = ["## Extension seams", ""]
    lines.append(
        "To add a connector, place it at "
        f"`{seams.add_connector_template}` and implement the `BaseConnector` "
        "Protocol **structurally** (a bare class — do NOT subclass it)."
    )
    lines.append("")

    lines.append("### Protocol seams")
    lines.append("")
    for proto in seams.protocols:
        lines.append(f"#### `{proto.name}` ({proto.location})")
        if proto.doc:
            lines.append("")
            lines.append(proto.doc)
        lines.append("")
        for method in proto.methods:
            qualifier = "async " if method.is_async else ""
            doc = f" — {method.doc}" if method.doc else ""
            lines.append(f"- `{qualifier}{method.name}(...)`{doc}")
        lines.append("")

    lines.append("### Convention seams")
    lines.append("")
    lines.append(
        "Not reflectable Protocols — conventions an implementer follows, with "
        "where each one lives:"
    )
    lines.append("")
    for conv in seams.conventions:
        lines.append(f"- **{conv.name}** — {conv.note}")
        lines.append(f"  - location: `{conv.location_template}`")
    lines.append("")
    return "\n".join(lines)


def _render_config_summary(config_schema: dict[str, Any]) -> str:
    """Render a shape-only summary of the config schema's top-level keys."""
    lines = ["## Configuration schema (shape only)", ""]
    lines.append(
        "Top-level keys of `MachinaConfig` (from `model_json_schema()`). Shape "
        "only — never any configured values:"
    )
    lines.append("")
    properties = config_schema.get("properties", {})
    if isinstance(properties, dict):
        for key in sorted(properties):
            prop = properties[key]
            description = ""
            if isinstance(prop, dict):
                description = prop.get("description", "") or ""
            # First sentence only, keep the summary compact.
            summary = description.split(". ")[0].strip()
            if summary:
                lines.append(f"- `{key}` — {summary}")
            else:
                lines.append(f"- `{key}`")
    defs = config_schema.get("$defs", {})
    if isinstance(defs, dict) and defs:
        lines.append("")
        lines.append("Nested config objects: " + ", ".join(f"`{name}`" for name in sorted(defs)))
    lines.append("")
    return "\n".join(lines)


def _render_gaps(spine: Spine) -> str:
    """Render the known-gaps section (orphaned caps + the settings note)."""
    lines = ["## Known gaps", ""]
    gaps = spine.gaps
    by_value = {c.value: c for c in spine.capabilities}
    if gaps.orphaned_capabilities:
        lines.append(
            "Capabilities in the vocabulary that **no registered connector** "
            "provides (declared only by connectors absent from the default "
            "factory registry — e.g. `SimulatedSensorConnector`):"
        )
        lines.append("")
        for value in gaps.orphaned_capabilities:
            note = by_value[value].orphan_note if value in by_value else ""
            lines.append(f"- **{value}** — {note}" if note else f"- **{value}**")
        lines.append("")
    if gaps.settings_note:
        lines.append(gaps.settings_note)
        lines.append("")
    return "\n".join(lines)


__all__ = [
    "PROVENANCE_END",
    "PROVENANCE_START",
    "UNCOMMITTED_SHA",
    "render_json",
    "render_markdown",
    "render_provenance_header",
    "strip_provenance",
]
